### ISSUE TITLE
Breaks With Virtual School

### ISSUE THREAD

**Issue by haylinmoore** [herohamp/DodeaGPACalculator#1]
When someone has virtual school it completly butchers the GPA, with people getting strange GPAs. The current theory is that the scraper located at https://github.com/herohamp/gradespeed-api-dodea.git is getting tripped up by the extra table. Sadly I do not have a way to test this, as I do not have a virtual school account.

**Comment by herohamp** [comment]
I'll need to request an account with virtual school, or ask someone to donate thier account to the cause

**Comment by herohamp** [comment]
the issue is probably located in https://github.com/herohamp/gradespeed-api-dodea.git

**Comment by haylinmoore** [comment]
It was fixed in ac3b7dc9a4dc6f5bb2229dbdd066ad897bea1f44
